{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$interval),\n  symbol AS metric,\n  avg(price) AS \"__connect_offset\"\nFROM \"<table>\"\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1, symbol,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$interval),\n  symbol AS metric,\n  avg(price)*avg(quantity) AS \"volume\"\nFROM \"<table>\"\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1, symbol,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Last volume",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  symbol AS metric,\n  avg(price) * avg(quantity) AS \"volume\"\nFROM \"<table>\"\nWHERE\n  $__timeFilter(ts)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Last Price",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  symbol as \"symbol\",\n  last(price,ts) AS \"price\"\nFROM \"<table>\"\nWHERE\n  $__timeFilter(ts)\nGROUP BY symbol\nORDER BY last(price, ts) desc"
    }
   ]
  }
 ]
}