version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        DOCKER_SOCKET_GIT: ${DOCKER_SOCKET_GID:-966}
        PROJECT_DIR: /workspace
    environment:
      PATH: /home/user/.nix-profile/bin:/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin
      KUBECONFIG: /home/user/.kube/config
      MINIKUBE_DRIVER: kvm2
      MINIKUBE_KVM_QEMU_URI: qemu+tcp://127.0.0.1:16509/system
      LIBVIRT_DEFAULT_URI: qemu+tcp://127.0.0.1:16509/system
    command: sleep infinity
    cap_add:
      # needed for telepresence
      - NET_ADMIN
      - NET_BIND_SERVICE
    volumes:
      - ..:/workspace:cached
      - pulumi:/home/user/.pulumi
      - minikube:/home/user/.minikube
      - kube:/home/user/.kube
      - direnv-allow:/home/user/.config/direnv/allow
      - nix:/nix
      - libvirt-lib:/var/lib/libvirt
      - libvirt:/run/libvirt
    security_opt:
      - label:disable
    depends_on:
      - libvirtd
      - socks5
    network_mode: "service:libvirtd"

  socks5:
    image: serjs/go-socks5-proxy
    restart: always
    network_mode: "service:libvirtd"

  libvirtd:
    image: xtruder/libvirtd:latest
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - libvirt:/run/libvirt
      - libvirt-lib:/var/lib/libvirt
      - libvirt-qemu:/var/lib/libvirt-qemu
      - minikube:/home/user/.minikube
    devices:
      - /dev/kvm
    network_mode: bridge

volumes:
  nix:
  kube:
  direnv-allow:
  pulumi:
  libvirt:
  libvirt-lib:
  libvirt-qemu:
  minikube: