version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    environment:
      PRELOAD_EXTENSIONS: "mkhl.direnv"
    cap_add:
      # needed for telepresence
      - NET_ADMIN
      - NET_BIND_SERVICE
    volumes:
      - ..:/workspace:cached
      - nix:/nix
      - pulumi:/home/code/.pulumi
      - kube:/home/code/.kube
      - minikube:/home/code/.minikube
    devices:
      - /dev/net/tun
      - /dev/kvm
    security_opt:
      - label:disable
    network_mode: "bridge"

volumes:
  nix:
  kube:
  pulumi:
  minikube:
